name: Build
on:
  push:
    branches:
      - master
      - branch-*
      - dogfood-*
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: github-ubuntu-latest-m
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
      - uses: SonarSource/ci-github-actions/build-maven@v1
        with:
          deploy-pull-request: true

  promote:
    needs: [build]
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
      - uses: SonarSource/ci-github-actions/promote@v1

  releasability:
    needs: [promote]
    if: >-
      github.ref_name == github.event.repository.default_branch ||
      startsWith(github.ref_name, 'branch-') ||
      startsWith(github.ref_name, 'dogfood-')
    runs-on: github-ubuntu-latest-s
    name: Releasability
    permissions:
      id-token: write
      statuses: write
      contents: read
    steps:
      - uses: SonarSource/gh-action_releasability/releasability-status@3.0.5
        with:
          optional_checks: "Jira"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
