name: Build
on:
  push:
    branches:
      - master
      - branch-*
      - dogfood-*
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: github-ubuntu-latest-m
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@9149ea85001c7435d5a66bb127d6a1b6227cb0a5 # v5.0.0
      - uses: SonarSource/ci-github-actions/build-maven@v2
        with:
          deploy-pull-request: true

  promote:
    needs: [build]
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@9149ea85001c7435d5a66bb127d6a1b6227cb0a5 # v5.0.0
      - uses: SonarSource/ci-github-actions/promote@v2
        with:
          promote-pull-request: true

  releasability:
    needs: [promote]
    if: >-
      github.ref_name == github.event.repository.default_branch ||
      startsWith(github.ref_name, 'branch-') ||
      startsWith(github.ref_name, 'dogfood-')
    runs-on: github-ubuntu-latest-s
    name: Releasability
    permissions:
      id-token: write
      statuses: write
      contents: read
    steps:
      - uses: SonarSource/gh-action_releasability/releasability-status@3.1.0
        with:
          optional_checks: "Jira"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  notify-build-failure:
    needs: [build, promote, releasability]
    if: >-
      always()
      && (github.ref_name == github.event.repository.default_branch || startsWith(github.ref_name, 'branch-') || startsWith(github.ref_name, 'dogfood-'))
      && contains(needs.*.result, 'failure')
    runs-on: github-ubuntu-latest-s
    permissions:
      actions: read
      id-token: write # required for vault-action-wrapper in the shared slack-notify action
    steps:
      - name: Slack Notification
        uses: SonarSource/core-languages-tooling-public/common-actions/slack-notify@v1
        with:
          slack-channel: squad-corelang-notifs
          branch-patterns: ${{ format('{0},branch-*,dogfood-*', github.event.repository.default_branch) }}
          github-token: ${{ github.token }}
          branch: ${{ github.ref_name }}
